### PR TITLE
C function Logos directives

### PR DESCRIPTION
**Pull request by uroboro**
Added %hookf and %origf directives for hooking C functions while supporting groups and using a variant of %orig.
%hookf takes a variadic number of arguments: the function return type, the function name, the function argument list. It generates the original function function pointer from these values and the current group.
%hookf takes a variadic number to pass to the original function, which is calculated from saving the current function name in %hookf and the current group.

### CODE REVIEW

**Comment by Tyilo** [comment]
Maybe add support for other functions than `MSHookFunction`? (eg. [rd_route](https://github.com/rodionovd/rd_route), [mach_override](https://github.com/rentzsch/mach_override))

Both of the functions they provide takes the same arguments in the same order as `MSHookFunction`, so you could just use `#define MSHookFunction rd_route`.
Maybe add a config option instead: `%config(hookf=rd_route)`?

**Comment by ryanb93** [comment]
Would be great to see this merged soon.

**Comment by rossistboss** [comment]
Why has this not been merged? Is there another way to hook C functions or something?

**Comment by youmingtaiziback** [comment]
Cool feature

**Pull request merged**
