### PR TITLE
Use additional temporary stage for package schemes 

### LINKED ISSUE #774: [Bug]: Stage contains empty directories when building for rootless
### What are the steps to reproduce this issue?

`deb.mk`

### What happens?

```make
ifeq ($(THEOS_PACKAGE_SCHEME),rootless)
 	$(ECHO_NOTHING)mkdir -p "$(THEOS_STAGING_DIR)$(THEOS_PACKAGE_INSTALL_PREFIX)"$(ECHO_END)
 	$(ECHO_NOTHING)rsync -a "$(THEOS_STAGING_DIR)/" "$(THEOS_STAGING_DIR)$(THEOS_PACKAGE_INSTALL_PREFIX)" --exclude "DEBIAN" --exclude "$(THEOS_PACKAGE_INSTALL_PREFIX)" $(_THEOS_RSYNC_EXCLUDE_COMMANDLINE) --remove-source-files$(ECHO_END)
 # Delete everything except DEBIAN/ and THEOS_PACKAGE_INSTALL_PREFIX
 	$(ECHO_NOTHING)find "$(THEOS_STAGING_DIR)" -mindepth 1 ! -path "*/DEBIAN*" ! -path "*$(THEOS_PACKAGE_INSTALL_PREFIX)*" \( -type d -empty -o -type f \) -delete$(ECHO_END)
 endif
```

### What were you expecting to happen?

In rootless mode, this part will cause additional var empty directories to appear in the generated package. The path is: `/var/jb/var`

### Paste any relevant logs, error output, etc.

_No response_

### Additional context

_No response_

### What OS are you seeing the problem on?

macOS

### What OS version does it have installed?

macOS 14

### What toolchain and version are you using?

Xcode 15.0

### Which SDK version are you using?

iOS 15.0

### What OS is your client device running?

iOS

### What OS version does it have installed?

iOS 15.1.1

### Which device model is it?

iPhone13 Pro Max

### Which jailbreak is it using (if relevant)?

Dopamine

### PR DESCRIPTION
**Pull request by L1ghtmann**
What does this implement/fix? Explain your changes.
---------------------------------------------------
- Stages first in $THEOS_STAGING_DIR
- Then creates a tmp stage with the install prefix
- Moves the top-level contents of $THEOS_STAGING_DIR, save for DEBIAN, to this new prefixed-stage 
- Moves the contents of the tmp dir (i.e., the install prefix) back to the main stage

Does this close any currently open issues?
------------------------------------------
Closes #774 
Resolves issue approached in #715 

Any relevant logs, error output, etc?
-------------------------------------

Any other comments?
-------------------
Note: quotes in `foreach` seem to break the logic. Likely want to fix that before merge 

Where has this been tested?
---------------------------
**Operating System:** …

Linux (WSL)

**Platform:** …

**Target Platform:** …

**Toolchain Version:** …

**SDK Version:** …

### CODE REVIEW

**Review by leptos-null — APPROVED** [review]

**Review by uroboro — APPROVED** [review]

**Review by leptos-null — COMMENTED** [review]
Overall architecture looks good to me. 
Latest commit fixes `_STAGE_CONTENTS ` for me, but the evaluation of `ifneq ($(call __theos_bool,$(_DEBIAN_ONLY)),$(_THEOS_TRUE))` is somehow not correct.

Specifically: 
`$(call __theos_bool,$(_DEBIAN_ONLY)) = 1`
`$(_THEOS_TRUE) = 1`
but then `ifneq` passes

**Comment by L1ghtmann** [comment]
K, think I fixed it again. Quick `tree` tests showed the expected result, but please confirm with your setup too in the event I introduced a regression again :/

**Comment by leptos-null** [comment]
Interesting fix. Testing looks good to me. Thanks again

**Comment by uroboro** [comment]
@L1ghtmann can you confirm if #715 can be closed?

**Comment by L1ghtmann** [comment]
I can confirm that the issue addressed in #715 has been resolved with this pr. @PoomSmart would you mind duly verifying when you have a moment?

**Comment by PoomSmart** [comment]
@L1ghtmann Yes, `/var/jb` is no longer under `_` stage folder. 👍🏻 

image

**Pull request merged**
