### PR TITLE
add roothide scheme support

### PR DESCRIPTION
**Pull request by RootHide**
What does this implement/fix? Explain your changes.
---------------------------------------------------
add roothide scheme support

Does this close any currently open issues?
------------------------------------------
none

Any relevant logs, error output, etc?
-------------------------------------

Any other comments?
-------------------
currently in c/c++/objc, we usually use THEOS_PACKAGE_INSTALL_PREFIX to determine rootful and rootless,
rootful's THEOS_PACKAGE_INSTALL_PREFIX is empty, while rootless's THEOS_PACKAGE_INSTALL_PREFIX is /var/jb, 
but for new schemes, different schemes may use different THEOS_PACKAGE_INSTALL_PREFIX, and different schemes may use same THEOS_PACKAGE_INSTALL_PREFIX.  so we cannot use THEOS_PACKAGE_INSTALL_PREFIX to determine scheme at compile time in c/c++/objc code.
so we need a new macro definition:
THEOS_PACKAGE_SCHEME_(SCHEME_NAME)

Where has this been tested?
---------------------------
**Operating System: macos12

**Platform: arm64e

**Target Platform: iphone11, ios15.1

**Toolchain Version: xcode14.2

**SDK Version: ios15.0, ios16.2

### CODE REVIEW

**Review by leptos-null — COMMENTED** [review]
The addition of `THEOS_PACKAGE_SCHEME_{scheme}` makes sense. I believe this is similar to `__arm__`, `__APPLE__` etc. macros.

The addition of `iphoneos-arm64e` is of little consequence to Theos itself, however accepting this into Theos sets a precedent in the jailbreak community to support this new "flag" (public repos, package managers, etc. may require updates).

Lastly, the addition of a new scheme implies the need for new support of some kind (packaging structure, link behaviors, etc.) which this PR does not provide. If this PR were to be merged, a theos/lib PR would need to be merged concurrently. What changes will be in `theos/vendor/lib/roothide`? Those changes need to be made in this repository as well so libraries/ frameworks can be compiled for this scheme.

**Comment by RootHide** [comment]
@leptos-null You are wise sir.

I will commit theos/vendor/lib/roothide later,
Its packaging structure uses theos default scheme (rootful), so it does not require additional processing.

**Comment by RootHide** [comment]
@leptos-null 
already committed libs, please review it sir.
https://github.com/theos/lib/pull/20

**Comment by leptos-null** [comment]
1. Theos and community members have discussed this and we do not believe that adding the `iphoneos-arm64e` architecture is a good idea for this.
2. This PR is no longer in an upstream-able state. Closing so that the author of this PR may continue to push to their `master` branch without impacting an open PR

**Pull request closed without merging**
