### PR TITLE
[package] Add ipa packaging support

### PR DESCRIPTION
**Pull request by uroboro**
What does this implement/fix? Explain your changes.
---------------------------------------------------
Adds ipa packaging for #286.

### CODE REVIEW

**Comment by uroboro** [comment]
This implementation relies on a single application being present in the project, but I hope that is the general case for making application projects. Otherwise, this will be delayed even more to implement mechanisms to package multiple apps from a single Theos project.

**Comment by kabiroberai** [comment]
IMO assuming that there’s only one app in the project is fine, since Xcode itself does the same thing when you archive a target. In particular, if it detects that any dependencies have install destinations outside the target’s app dir (/Applications/[app name].app), it won’t let you export the archive as an ipa file.

**Comment by leptos-null** [comment]
This PR looks good, and very helpful. 
The requirement of a `control` file is a dpkg concept, where an `Info.plist` is the somewhat-equivalent for an ipa. The two fields from the `control` file (Package, Version) are also present in a bundle `Info.plist` (CFBundleIdentifier, CFBundleVersion). I understand this is a fairly small detail, and that a method for reading plists is not portably available.

**Comment by kirb** [comment]
Merged into [next](https://github.com/theos/theos/compare/master...next) branch. Needs testing.

**Pull request closed without merging**
