### PR TITLE
Fix `install.exec` locally for iOS/macOS

### PR DESCRIPTION
**Pull request by Diatrus**
Adds compatibility with BSD su, which macOS and Procursus both take advantage of. Continues to work on Linux su.

### CODE REVIEW

**Review by PoomSmart — APPROVED** [review]

**Comment by nanish94** [comment]
diatrus:patch-1 theos:master

**Review by Mixcnx — COMMENTED** [review]
git clone https://github.com/akemin-dayo/AppSync.git
cd AppSync/
make
make package

**Review by Mixcnx — COMMENTED** [review]
git clone https://github.com/akemin-dayo/AppSync.git
cd AppSync/
make
make package

**Review by Mixcnx — COMMENTED** [review]
git clone https://github.com/akemin-dayo/AppSync.git
cd AppSync/
make
make package

**Review by Mixcnx — COMMENTED** [review]
git clone https://github.com/akemin-dayo/AppSync.git
cd AppSync/
make
make package

**Pull request merged**
