### PR TITLE
Update 64bit

### PR DESCRIPTION
**Pull request by Dry05**
hi could you please update theos jailed for 64bit devices? Regards Bas

### CODE REVIEW

**Comment by ahyattdev** [comment]
Please merge this! They all look like great improvements.

**Comment by Dry05** [comment]
I'm sorry I wouldn't know but are you gonna update theos-jailed for 64bit devices please?
Kind regards Bas

Verstuurd vanaf mijn iPhone

**Comment by kirb** [comment]
This can’t be merged on its own. This makes changes to Theos that would break support for jailbroken devices.

**Comment by Dry05** [comment]
But could one of you please update Bishopfox/theos-jailed for 64bit devices?

**Comment by kirb** [comment]
It doesn't seem any of the upstream Theos developers (us) are interested in this. Your best bet is to get in touch with the developers of the theos-jailed fork.

**Pull request closed without merging**
