### PR TITLE
Pass -Zgzip to dpkg-deb for backwards compatibility

### PR DESCRIPTION
**Pull request by moloch--**
Quick fix for issue https://github.com/DHowett/theos/issues/69

### CODE REVIEW

**Comment by PaulBGD** [comment]
Still fixes it, still not pulled. Thanks!

**Comment by kirb** [comment]
I would advise against using gzip. The actual problem here is that the dpkg version on the build machine is newer than the dpkg version in Telesphoreo. The latest dpkg supports (in order of compression ratio provided): gzip, bzip2, lzma, and xz. Telesphoreo’s dpkg build supports all of those except for xz. Therefore, the next best choice is lzma.

The flag `-Zlzma` was added some time ago in kirb/theos, which is now merged into this repo, so this PR can be closed.

**Comment by ThePantsThief** [comment]
So are we all supposed to manually change it to gzip until Telesphoreo updates dpkg…?

**Comment by kirb** [comment]
Telesphoreo dpkg supports LZMA, and this is the default.

**Comment by ThePantsThief** [comment]
Oh. Do you have any idea why I'm getting an unsupported compression type error about it when I try to build a deb then?

--
Tanner Bennett

**Comment by PaulBGD** [comment]
I'm still getting it too, this PR still fixes it.

**Comment by DHowett** [comment]
That sounds like it's happening at build time and will have no bearing on
how it performs on-device.

Fwiw, this is precisely why I didn't want to set a default; reaching the
best supported feature set between commonly available dpkg versions is
fairly painful :p

bzip2 is likely to be the most widely supported version apart from gzip,
and it provides better ratios.

**Comment by ThePantsThief** [comment]
Yeah, exactly haha. Does anyone know off the top of their head where to get a version for OS X that works with this?

--
Tanner Bennett

**Comment by DHowett** [comment]
macports fairly expertly packages a wide range of updated versions of cool
things. This includes dpkg. :)

**Comment by ThePantsThief** [comment]
Thanks G :)

--
Tanner Bennett

**Comment by jackiossy** [comment]
How to fix it ?

**Pull request closed without merging**
