### PR TITLE
Update Fedora Install Script

### PR DESCRIPTION
**Pull request by Desyncfy**
What does this implement/fix? Explain your changes.
---------------------------------------------------
The current script does not work on Fedora 41, so I have changed it to do so. The issues lies in trying to install the group by the name rather than the id, which is the (current) functionality. (See more at https://dnf5.readthedocs.io/en/latest/changes_from_dnf4.7.html)

Does this close any currently open issues?
------------------------------------------
No

Any relevant logs, error output, etc?
-------------------------------------
```bash
Failed to resolve the transaction:
No match for argument: Development Tools
You can try to add to command line:
  --skip-unavailable to skip unavailable packages
==> Dependency install command seems to have encountered an error. Please see the log above.
```

Any other comments?
-------------------
Nope!

Where has this been tested?
---------------------------
**Operating System:** Fedora 41

**Platform:** Framework Laptop 13 _AMD Ryzen 7040Series_

**Target Platform:** N/A

**Toolchain Version:** N/A

**SDK Version:** N/A

### CODE REVIEW

**Comment by L1ghtmann** [comment]
Hey, thanks a ton for opening this. Do you know if the id version is backwards compatible?

**Comment by Desyncfy** [comment]
@L1ghtmann Opening a fedora 40 vm to see. It should work, but if it doesn't I can probably write a check to make it backwards compatible

**Comment by Desyncfy** [comment]
Alright. Confirmed it works

**Review by L1ghtmann — APPROVED** [review]
Thanks so much for identifying the fix and checking compatibility!

**Pull request merged**
