### PR TITLE
`make uninstall` should unload target processes

### PR DESCRIPTION
**Pull request by NSExceptional**
Is there an approach to this other than just copy-pasting the content of internal-after-install? Or is this fine? My `make` skills aren't very sharp

### CODE REVIEW

**Comment by kabiroberai** [comment]
Nine months late but I've incorporated this into the orion branch

**Comment by NSExceptional** [comment]
I don't know what Orion is but is there a reason this can't go directly to master?

**Comment by kabiroberai** [comment]
I can't merge this directly because there's some other changes I had to make to your PR in order to make the uninstallation semantics correct so I'd like those to go through review as well.

**Comment by NSExceptional** [comment]
Oh. Well you could always add those changes here, I think I checked the "give maintainers commit access" box 😅

**Comment by kabiroberai** [comment]
I just tried to cherry-pick da102a8 into your branch but it seems that I don't have write access.

**Comment by NSExceptional** [comment]
Weird, I don't see the option anywhere. I wonder if it's because the fork is under an organization.

Anyway, never mind! As long as it'll make it's way into master. Should you open another PR with the changes or does the Orion branch regularly get merged with master?

**Comment by kabiroberai** [comment]
I'm planning to open a PR for Orion once the [theos/orion](https://github.com/theos/orion) repo is made public, which should hopefully be pretty soon. You can check out https://orion.theos.dev for info on what it is.

**Comment by NSExceptional** [comment]
Ohh, gotcha. In that case, I added you as a contributor, so you should be able to do that cherry-pick now

**Comment by kabiroberai** [comment]
Done, please confirm that my commits work on your end after which I'll merge this.

**Comment by NSExceptional** [comment]
It works!

**Review by kabiroberai — APPROVED** [review]

**Pull request merged**
